# Generated by Django 4.2.7 on 2023-11-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pandit',
            name='desc',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pandit',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='puja',
            name='desc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='puja',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
