# Generated by Django 4.2.7 on 2023-11-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_pandit_age_alter_pandit_desc_alter_pandit_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandit',
            name='age',
        ),
    ]
