# Generated by Django 4.2.7 on 2023-11-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_pandit_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit',
            name='skills',
            field=models.ManyToManyField(to='app1.puja'),
        ),
    ]
