# Generated by Django 4.2.7 on 2023-11-25 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0005_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Book for date')),
                ('pandit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.pandit')),
                ('puja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.puja')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
