# Generated by Django 4.2.7 on 2023-11-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_booking_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puja',
            name='desc',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
