# Generated by Django 4.2.5 on 2024-09-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit',
            name='pandit_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
