# Generated by Django 4.2.5 on 2024-09-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_pandit_pandit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit',
            name='experience',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
