# Generated by Django 4.2.5 on 2024-09-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_pandit_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='puja',
            name='puja_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
