# Generated by Django 4.2.5 on 2024-09-13 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_puja_puja_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True, verbose_name='Book for date'),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.booking')),
                ('pandit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pandit')),
            ],
        ),
    ]
